## Import Library

In [6]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

## Data Prepocessing

In [7]:
training_set = tf.keras.utils.image_dataset_from_directory(
    'train',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False
)

Found 16643 files belonging to 9 classes.


## Validation Image processing

In [9]:
validation_set = tf.keras.utils.image_dataset_from_directory(
    'valid',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False
)

Found 4160 files belonging to 9 classes.


In [10]:
training_set

<BatchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 9), dtype=tf.float32, name=None))>

In [11]:
for (x,y) in training_set:
    print(x,x.shape)
    print(x,y.shape)
    break

tf.Tensor(
[[[[ 98.75  94.75  91.75]
   [113.75 109.75 106.75]
   [100.    96.    93.  ]
   ...
   [158.25 158.25 160.25]
   [154.5  154.5  156.5 ]
   [155.75 155.75 157.75]]

  [[ 97.25  93.25  90.25]
   [ 98.75  94.75  91.75]
   [100.    96.    93.  ]
   ...
   [159.5  159.5  161.5 ]
   [160.25 160.25 162.25]
   [160.   160.   162.  ]]

  [[109.75 105.75 102.75]
   [106.5  102.5   99.5 ]
   [104.5  100.5   97.5 ]
   ...
   [156.75 156.75 158.75]
   [157.75 157.75 159.75]
   [164.   164.   166.  ]]

  ...

  [[133.   131.   136.  ]
   [137.25 135.25 140.25]
   [133.75 131.75 136.75]
   ...
   [171.5  170.5  175.5 ]
   [174.   173.   178.  ]
   [173.   172.   177.  ]]

  [[130.5  128.5  133.5 ]
   [131.75 129.75 134.75]
   [127.25 125.25 130.25]
   ...
   [167.75 166.75 171.75]
   [170.75 169.75 174.75]
   [172.   171.   176.  ]]

  [[136.25 134.25 139.25]
   [130.25 128.25 133.25]
   [128.5  126.5  131.5 ]
   ...
   [167.5  166.5  171.5 ]
   [171.25 170.25 175.25]
   [174.5  173.5  17

## Building Model

In [30]:
cnn = tf.keras.models.Sequential()

In [31]:
cnn.add(tf.keras.layers.Conv2D(filters=32,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
cnn.add(tf.keras.layers.Conv2D(filters=32,kernel_size=3,activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2,strides=2))

In [32]:
cnn.add(tf.keras.layers.Conv2D(filters=64,kernel_size=3,padding='same',activation='relu'))
cnn.add(tf.keras.layers.Conv2D(filters=64,kernel_size=3,activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2,strides=2))

In [33]:
cnn.add(tf.keras.layers.Conv2D(filters=128,kernel_size=3,padding='same',activation='relu'))
cnn.add(tf.keras.layers.Conv2D(filters=128,kernel_size=3,activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2,strides=2))

In [34]:
cnn.add(tf.keras.layers.Conv2D(filters=256,kernel_size=3,padding='same',activation='relu'))
cnn.add(tf.keras.layers.Conv2D(filters=256,kernel_size=3,activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2,strides=2))

In [35]:
cnn.add(tf.keras.layers.Conv2D(filters=512,kernel_size=3,padding='same',activation='relu'))
cnn.add(tf.keras.layers.Conv2D(filters=512,kernel_size=3,activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2,strides=2))

In [36]:
cnn.add(tf.keras.layers.Dropout(0.25))

In [37]:
cnn.add(tf.keras.layers.Flatten())

In [38]:
cnn.add(tf.keras.layers.Dense(units=1500,activation='relu'))

In [39]:
cnn.add(tf.keras.layers.Dropout(0.4)) #To avoid overfitting

In [40]:
#Output Layer
cnn.add(tf.keras.layers.Dense(units=9,activation='softmax'))

## Compiling and Training Phase

In [41]:
cnn.compile(optimizer=tf.keras.optimizers.legacy.Adam(
    learning_rate=0.0001),loss='categorical_crossentropy',metrics=['accuracy'])

In [42]:
cnn.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_10 (Conv2D)          (None, 128, 128, 32)      896       
                                                                 
 conv2d_11 (Conv2D)          (None, 126, 126, 32)      9248      
                                                                 
 max_pooling2d_5 (MaxPooling  (None, 63, 63, 32)       0         
 2D)                                                             
                                                                 
 conv2d_12 (Conv2D)          (None, 63, 63, 64)        18496     
                                                                 
 conv2d_13 (Conv2D)          (None, 61, 61, 64)        36928     
                                                                 
 max_pooling2d_6 (MaxPooling  (None, 30, 30, 64)       0         
 2D)                                                  

In [43]:
training_history = cnn.fit(x=training_set,validation_data=validation_set,epochs=10)

Epoch 1/10
521/521 [==============================] - 527s 1s/step - loss: 1.2300 - accuracy: 0.5585 - val_loss: 0.6265 - val_accuracy: 0.7853
Epoch 2/10
521/521 [==============================] - 520s 999ms/step - loss: 0.5425 - accuracy: 0.8109 - val_loss: 0.4200 - val_accuracy: 0.8560
Epoch 3/10
521/521 [==============================] - 519s 997ms/step - loss: 0.3735 - accuracy: 0.8677 - val_loss: 0.3460 - val_accuracy: 0.8748
Epoch 4/10
521/521 [==============================] - 519s 996ms/step - loss: 0.2582 - accuracy: 0.9114 - val_loss: 0.2217 - val_accuracy: 0.9243
Epoch 5/10
521/521 [==============================] - 519s 996ms/step - loss: 0.1941 - accuracy: 0.9311 - val_loss: 0.2912 - val_accuracy: 0.8974
Epoch 6/10
521/521 [==============================] - 520s 998ms/step - loss: 0.1587 - accuracy: 0.9451 - val_loss: 0.1754 - val_accuracy: 0.9423
Epoch 7/10
521/521 [==============================] - 520s 998ms/step - loss: 0.1203 - accuracy: 0.9596 - val_loss: 0.2762 - va

## Evaluating Model

In [44]:
#Training set Accuracy
train_loss, train_acc = cnn.evaluate(training_set)
print('Training accuracy:', train_acc)

521/521 [==============================] - 130s 249ms/step - loss: 0.0977 - accuracy: 0.9689
Training accuracy: 0.9689359068870544


In [ ]:
#Validation set Accuracy
val_loss, val_acc = cnn.evaluate(validation_set)
print('Validation accuracy:', val_acc)

104/130 [=======================>......] - ETA: 6s - loss: 0.3021 - accuracy: 0.9252

## Saving Model

In [ ]:
cnn.save('trained_plant_disease_model.keras')

In [ ]:
training_history.history #Return Dictionary of history

In [ ]:
#Recording History in json
import json
with open('training_hist.json','w') as f:
  json.dump(training_history.history,f)

## Accuracy Visualization

In [ ]:
epochs = [i for i in range(1,11)]
plt.plot(epochs,training_history.history['accuracy'],color='red',label='Training Accuracy')
plt.plot(epochs,training_history.history['val_accuracy'],color='blue',label='Validation Accuracy')
plt.xlabel('No. of Epochs')
plt.title('Visualization of Accuracy Result')
plt.legend()
plt.show()

In [ ]:
import json 
import matplotlib.pyplot as plt

# Memuat model
model = tf.keras.models.load_model('trained_plant_disease_model.keras')

# Memuat history training
with open('training_hist.json', 'r') as f:
    training_history = json.load(f)


## Some other metrics for model evaluation

In [ ]:
class_name = validation_set.class_names
class_name

In [ ]:
test_set = tf.keras.utils.image_dataset_from_directory(
    'valid',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=1,
    image_size=(128, 128),
    shuffle=False,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False
)

In [ ]:
y_pred = cnn.predict(test_set)
predicted_categories = tf.argmax(y_pred, axis=1)

In [ ]:
true_categories = tf.concat([y for x, y in test_set], axis=0)
Y_true = tf.argmax(true_categories, axis=1)

In [ ]:
Y_true

In [ ]:
predicted_categories

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report
cm = confusion_matrix(Y_true,predicted_categories)

In [ ]:
# Precision Recall Fscore
print(classification_report(Y_true,predicted_categories,target_names=class_name))

In [ ]:
plt.figure(figsize=(40, 40))
sns.heatmap(cm,annot=True,annot_kws={"size": 10})

plt.xlabel('Predicted Class',fontsize = 20)
plt.ylabel('Actual Class',fontsize = 20)
plt.title('Plant Disease Prediction Confusion Matrix',fontsize = 25)
plt.show()